//
// This file was generated by the Eclipse Implementation of JAXB, v3.0.0 
// See https://eclipse-ee4j.github.io/jaxb-ri 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2024.08.13 at 11:34:08 AM EEST 
//

@jakarta.xml.bind.annotation.XmlSchema(namespace = "http://www.example.org/calculator/", elementFormDefault = jakarta.xml.bind.annotation.XmlNsForm.QUALIFIED)
package com.exalt.training.soapcalculator.jaxb;
